### ISSUE TITLE
implement stroke tessellator on top of fill tessellator

### ISSUE THREAD

**Issue by LU15W1R7H** [nical/lyon#644] opened 2021-04-15 20:16 UTC
Would it be possible to implement the stroke tessellator not as a seperate tessellator but instead as a higher level abstraction, which just uses the fill tessellator.

The stroker takes a linear path describing a curve you want to have drawn with a stroke. The stroker then converts this path into the stroked outline and gives this to the filler which does the actual tessellation.

This would be very nice, because then we could have only one true tessellator and build on top of that.
This would reduce a big amount of complexity (better maintainable) and still preserve the same functionality (hopefully).

**Comment by nical** [comment] 2021-04-16 14:25
Yes, it would be possible and valuable to have this (that's what I meant in #564). The way this is commonly done is via a simple stroke-to-fill conversion routine that is tessellated using the non-zero fill rule to properly handle self-intersections. It would be much slower than the current stroke tessellator which gets a lot of speed from its naïve algorithm, but it would give more correct results in some situations where the current stroke tessellator falls a bit short.

I'd still keep the naïve stroke tessellator at least for a until evaluating the performance impact on practical use cases. The current stroke tessellator is a rather simple algorithm so it hasn't caused much maintenance burden so far.

If you are interested in giving it a go, there is a license-compatible implement of the stroke-to-fill conversion algorithm that you can take inspiration from in pathfinder: https://github.com/pcwalton/pathfinder/blob/ce3b40cd5c9e73dcfa71e38702e516caf479451d/content/src/stroke.rs#L50

**Comment by nical** [comment] 2021-06-06 09:34
Closing as duplicate of #564.

**Closed by nical** 2021-06-06 09:34 UTC
