### ISSUE TITLE
lyon_tessellation: overflow issues with large coordinate values

### ISSUE THREAD

**Issue by Lapz** [nical/lyon#354] opened 2018-05-26 11:33 UTC
If you clone [Lapz/game_playground](https://github.com/Lapz/game_playground) and checkout the perlin branch and run the program it panics with attempt to subtract with overflow.
Here is the stack trace

``` rust 
  0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:463
   5: std::panicking::try::do_call
             at libstd/panicking.rs:350
   6: std::panicking::try::do_call
             at libstd/panicking.rs:328
   7: <core::fmt::Write::write_fmt::Adapter<'a, T> as core::fmt::Write>::write_str
             at libcore/panicking.rs:71
   8: <core::fmt::Write::write_fmt::Adapter<'a, T> as core::fmt::Write>::write_str
             at libcore/panicking.rs:51
   9: <lyon_tessellation::fixed::_16 as lyon_tessellation::fixed::FractionalBits>::bits
             at /Users/lenardpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.1/src/fixed.rs:245
  10: <alloc::alloc::Global as core::alloc::GlobalAlloc>::realloc
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.17.3/src/point.rs:176
  11: lyon_tessellation::path_fill::FillTessellator::tessellator_loop
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.1/src/path_fill.rs:431
  12: lyon_tessellation::path_fill::PendingEdge::to_active_edge
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.1/src/path_fill.rs:352
  13: <ggez::graphics::types::LinearColor as core::convert::From<ggez::graphics::types::Color>>::from::f
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.1/src/path_fill.rs:327
  14: lyon_tessellation::FillOptions::default
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.1/src/basic_shapes.rs:816
  15: ggez::filesystem::Filesystem::is_file::{{closure}}
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mesh.rs:162
  16: ggez::graphics::mesh::MeshBuilder::polygon::{{closure}}
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mesh.rs:310
  17: <ggez::graphics::SamplerCache<B>>::get_or_insert::{{closure}}
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mod.rs:455
  18: <ggez::graphics::SamplerCache<B>>::get_or_insert::{{closure}}
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/graphics/mod.rs:486
  19: <game_playground::MainState as ggez::event::EventHandler>::draw
             at src/main.rs:51
  20: ggez::event::run
             at /Users/rowlandsonpratt/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.2/src/event.rs:283
  21: game_playground::main
             at src/main.rs:71
  22: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  23: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  24: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  25: <alloc::string::String as core::fmt::Display>::fmt
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  26: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74

```

**Comment by nical** [comment] 2018-05-27 13:15
Thanks for filing this!
I checked out the perlin branch and did `cargo run` but couldn't reproduce the issue (I get a black window). By the look of the stack trace this is caused by the fact that the fill tessellator internally uses 16.16 fixed point numbers and this test case is hitting the maximum/minimum values that can be represented that way which is unfortunately not that big (around the [-32767.0 .. 32767.0] range).

I'd like to be able to check that it's really the case, though.

I am working on a new tessellation algorithm that doesn't use fixed point numbers, but it will take a while until it is on par with the current algorithm.

**Comment by Lapz** [comment] 2018-05-29 09:33
The issue was caused by a problem in my perlin algorthim and a such I changed the code to fix the problem. I've made another repo which contains the [problematic code](https://github.com/Lapz/lyon_perlin)

**Comment by nical** [comment] 2018-05-29 09:55
Thanks! I confirmed that the problem is indeed the limited range that the tessellator is able to represent internally.
Overcoming this limitation is definitely something that I want to do but it will take a while before the new tessellator that lifts this restriction is usable, so in the meanwhile you have two options:

- Scale your data so that it fits in a smaller range and scale it back up again when generating the triangles.
- Use the libtess2 tessellator that is exposed by lyon_tess2. It will let you use [libtess2](https://github.com/memononen/libtess2) instead of lyon's default tessellator. libtess2 is slower and adds a dependency to a C library, but it can cover a larger coordinate range.

**Comment by nical** [comment] 2019-12-23 10:00
Fixed in the tessellator rewrite that just made it into the master branch. Release coming in a few days.

**Closed by nical** 2019-12-23 10:00 UTC
