### ISSUE TITLE
Stroke Tessellation seems to produce incorrect output when with_line_width > 1.0

### ISSUE THREAD

**Issue by bgaster** [nical/lyon#462] opened 2019-03-25 09:29 UTC
When tessellating a stoke for the following 

```rust
builder.move_to(point(30.0000,170.0000));
builder.cubic_bezier_to(point(36.9017, 162.6667), point(40.7360, 126.0000), point(41.5029, 60.0000));
builder.line_to(point(41.5029,170.0000));
builder.line_to(point(30.0000,170.0000));
```

I get the correct output, if `with_line_width(1.0)` on the stoke_options, however, if line width is increased, then there are outlying triangles generated. 

This issue can be reproduced using the following SVG:

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 320 240" style="enable-background:new 0 0 320 240;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#00FFFF;stroke:#000000;stroke-miterlimit:10;}
	.st1{fill:none;stroke:#000000;stroke-miterlimit:10;}
</style>

<path class="st0" d="
	M30 170
	Q40.3525848 159, 41.502872 60
	L41.502872 170
	L30 170
	"/>
</svg>
```

and then in `svg_render/src/main.rs`, change line 133 to:

```rust
   &stroke_opts.with_tolerance(0.01).with_line_width(3.0),
```

The displayed output can be seen to having a line breaking out of the curved triangle, which should not be the case, and does not happen when `with_line_width(1.0)`.

**Comment by nical** [comment] 2019-03-26 15:42
Thanks for providing a test case! I'll look into this soon.

**Comment by nical** [comment] 2019-03-30 20:29
Sorry for my lack of reactivity. I looked into this and the issue is caused by the rather naive way the stroke tessellator figures out the tessellation of joins. The approach has this tendency to misbehave with very sharp angles when the line width is such that the next vertex (let's say C in the gribble below) is inside of the stroke on the edge AB (and vis-versa).

```ascii
   B
  / \
 /   C
A
```

It's not an easy thing to fix but I'll try to think of something.

**Comment by bgaster** [comment] 2019-04-02 10:39
Thanks for letting me know. Hopefully you will find a solution.

**Comment by Dollab** [comment] 2019-06-18 08:16
@nical I've made a quick (and somewhat dirty fix) of this problem for a personal project. 
I've encountered two issues : 
• when the stroke of the next edge overlaps the stroke of the previous edge (in the case of a sharp angle) the normal for the back of the join is too long. I've solved this by computing the normal so as to put the back join vertex at the intersection of the previous edge and the next edge. This does create a collinear triangle.
• when one of the edge of the join is very small and has a length < to the line_width/2.0 the tessellator behaves in a discontinuous way that is not compliant with svg standard. I've solved this in a hacky way by fixing the normal when the edge length is under a certain size. The correct way would be to compute two different vertices for the back join.
If you'd like I can try to make a cleaner PR.

**Comment by Dollab** [comment] 2019-06-18 08:25
Example of the behavior of the path stroke tessellator (current)
![path_tessellator](https://user-images.githubusercontent.com/7534544/59665518-59023080-91b3-11e9-8b72-55da8ccfc938.gif)

**Comment by Dollab** [comment] 2019-06-18 08:26
![path_tessellator_v2](https://user-images.githubusercontent.com/7534544/59665556-71724b00-91b3-11e9-8bf1-e6a070daacfa.gif)
Example of the proposed behavior

**Comment by nical** [comment] 2019-06-18 15:48
@Dollab great! I would be very grateful if you submitted a PR!

**Comment by Dollab** [comment] 2019-06-20 20:45
Hi @nical , I've submitted a PR that should fix the stroke tessellator in the case of overlapping strokes :  
👉 [447](https://github.com/nical/lyon/pull/477)
Example of the tessellator behavior : 
![tessellation](https://user-images.githubusercontent.com/7534544/59880304-01c7b000-93ad-11e9-8bb8-292d2ce949b4.gif)

**Comment by nical** [comment] 2019-12-23 10:26
#447 landed a while ago, thanks to @Dollab. Closing.

**Closed by nical** 2019-12-23 10:26 UTC
Labels: bug
